# Generated by Django 4.0.6 on 2022-09-14 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import doctor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=doctor.models.Doctor.get_upload_path)),
                ('registration_number', models.CharField(blank=True, max_length=255, null=True)),
                ('clinic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('clinic_registration_number', models.CharField(blank=True, max_length=255, null=True)),
                ('digital_signature', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('address_proof_of_clinic_regetration', models.FileField(blank=True, null=True, upload_to=doctor.models.Doctor.get_upload_path)),
                ('degree_certificate', models.FileField(blank=True, null=True, upload_to=doctor.models.Doctor.get_upload_path)),
                ('doctor_regestration_no_proof', models.FileField(blank=True, null=True, upload_to=doctor.models.Doctor.get_upload_path)),
                ('clinic_regestration_certificate', models.FileField(blank=True, null=True, upload_to=doctor.models.Doctor.get_upload_path)),
                ('document1', models.FileField(blank=True, null=True, upload_to=doctor.models.Doctor.get_upload_path)),
                ('document2', models.FileField(blank=True, null=True, upload_to=doctor.models.Doctor.get_upload_path)),
                ('document3', models.FileField(blank=True, null=True, upload_to=doctor.models.Doctor.get_upload_path)),
                ('document4', models.FileField(blank=True, null=True, upload_to=doctor.models.Doctor.get_upload_path)),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('experience_years', models.IntegerField(blank=True, default=0, null=True)),
                ('is_del', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee', models.IntegerField(default=200)),
                ('timeslot', models.IntegerField(default=15)),
                ('qualification_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.qualification')),
                ('specilization_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.speciality')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('start_time', models.TimeField(verbose_name='start Time')),
                ('end_time', models.TimeField(verbose_name='end Time')),
                ('is_del', models.BooleanField(default=False)),
                ('is_in_schedul', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorRatingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('review', models.CharField(max_length=1000)),
                ('is_del', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_mode', models.CharField(choices=[('offline', 'offline'), ('online', 'online')], max_length=100, null=True)),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(null=True, verbose_name='end date')),
                ('start_time', models.TimeField(verbose_name='start Time')),
                ('end_time', models.TimeField(null=True, verbose_name='end Time')),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('is_del', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('start_time', models.TimeField(verbose_name='start Time')),
                ('end_time', models.TimeField(verbose_name='end Time')),
                ('is_del', models.BooleanField(default=False)),
                ('is_done_appointment', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
